
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorjflexcup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FPAR = 23;
  public static final int OU = 15;
  public static final int ELSE = 19;
  public static final int INT = 26;
  public static final int IGUAL = 7;
  public static final int MAIORQ = 9;
  public static final int WHILE = 20;
  public static final int APAR = 22;
  public static final int MAIORI = 11;
  public static final int IF = 18;
  public static final int MENORQ = 10;
  public static final int ID = 16;
  public static final int ATRIB = 6;
  public static final int SUB = 5;
  public static final int E = 14;
  public static final int MENORI = 12;
  public static final int EOF = 0;
  public static final int MULT = 3;
  public static final int NAO = 13;
  public static final int DIV = 4;
  public static final int CONST = 17;
  public static final int error = 1;
  public static final int STR = 24;
  public static final int BOOL = 25;
  public static final int WS = 27;
  public static final int ERRO = 21;
  public static final int SOMA = 2;
  public static final int DIF = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOMA",
  "MULT",
  "DIV",
  "SUB",
  "ATRIB",
  "IGUAL",
  "DIF",
  "MAIORQ",
  "MENORQ",
  "MAIORI",
  "MENORI",
  "NAO",
  "E",
  "OU",
  "ID",
  "CONST",
  "IF",
  "ELSE",
  "WHILE",
  "ERRO",
  "APAR",
  "FPAR",
  "STR",
  "BOOL",
  "INT",
  "WS"
  };
}

